name: Linting
on: [pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
  dockerlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile
          lint: 'hadolint'
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - uses: DavidAnson/markdownlint-cli2-action@v15
      with:
        config: '.markdownlint.jsonc'
        globs: '**/*.md'
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Image
        uses: docker/build-push-action@v2
        with:
          push: false